package database

import (
	"context"
	"fmt"
	"pet-project/internal/config"

	"github.com/jackc/pgx/v5/pgxpool"
)

func NewPool(ctx context.Context, cfg config.PostgresConfig) (*pgxpool.Pool, error) {
	poolCfg, err := pgxpool.ParseConfig(cfg.DSN)
	if err != nil {
		return nil, fmt.Errorf("parse pool config: %w", err)
	}

	poolCfg.MaxConns = int32(cfg.MaxConns)
	poolCfg.MinConns = int32(cfg.MinConns)
	poolCfg.MaxConnLifetime = cfg.MaxConnLifetime

	pool, err := pgxpool.NewWithConfig(ctx, poolCfg)
	if err != nil {
		return nil, fmt.Errorf("create pool: %w", err)
	}

	if err := pool.Ping(ctx); err != nil {
		return nil, fmt.Errorf("ping db: %w", err)
	}

	return pool, nil
}

// Пока без миграций, просто скрипты на создание бд
func CreateTableUser(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx,
		`CREATE TABLE IF NOT EXISTS users(
				id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name VARCHAR(80) NOT NULL,
				email VARCHAR(255) NOT NULL UNIQUE,
				password_hash TEXT NOT NULL,
				balance NUMERIC(12, 2) NOT NULL DEFAULT 0
			);`)
	if err != nil {
		return ErrorCreateDB("User", err)
	}

	return nil
}

func CreateTableCategory(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx,
		`CREATE TABLE IF NOT EXISTS category(
				id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name VARCHAR(50) NOT NULL UNIQUE
			);`)
	if err != nil {
		return ErrorCreateDB("Category", err)
	}

	return nil
}

func CreateTableProduct(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx,
		`CREATE TABLE IF NOT EXISTS product(
				id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name VARCHAR(255) NOT NULL,
				description TEXT NOT NULL,
				price NUMERIC(12,2) NOT NULL CHECK(price > 0),
				quantity INT NOT NULL DEFAULT 0 CHECK(quantity >= 0),
				category_id INT NOT NULL REFERENCES category(id)
			);`)

	if err != nil {
		return ErrorCreateDB("Product", err)
	}

	return nil
}

func CreateTableOrder(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx,
		`CREATE TABLE IF NOT EXISTS orders(
				id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				user_id INT NOT NULL REFERENCES users(id),
				ordered_at TIMESTAMP NOT NULL
			);`)

	if err != nil {
		return ErrorCreateDB("Order", err)
	}

	return nil
}

func CreateTableOrderItem(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx,
		`CREATE TABLE IF NOT EXISTS orders_item(
				id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				order_id INT NOT NULL REFERENCES orders(id),
				product_id INT NOT NULL REFERENCES product(id),
				quantity INT NOT NULL CHECK(quantity > 0)
			);`)
	if err != nil {
		return ErrorCreateDB("OrderItem", err)
	}

	return nil
}
